NUM_EPISODES = 2000
MAX_SPEED = 64
MIN_SPEED = 2
MAX_DEPTH = 128
MODELS_DIR = "models"
CAUTON_PROXIMITY = 10
MAX_SPEED_REWARD = 5
MAX_DIST_REWARD = 3
KILL_PENALTY = 10

CHANNELS_PER_FRAME = 2
FRAME_RATE = 32