NUM_EPISODES = 2000
MAX_SPEED = 20
MIN_SPEED = 1
MAX_DEPTH = 128
MODELS_DIR = "models"
CAUTON_PROXIMITY = 7
KILL_PENALTY = 10

CHANNELS_PER_FRAME = 3
FRAME_RATE = 32

MAX_SPEED_REWARD = 1
MAX_DIST_REWARD = 2